### ISSUE TITLE
Support Cocoapods 0.36

### ISSUE THREAD

**Issue by valeriomazzeo** [mattt/FormatterKit#158]
At the moment FormatterKit crashes when installed through version of cocoapods 0.36+

The main change is that now the resources bundle are not included into the main one, but they are inside the framework. You can find more information here: http://blog.cocoapods.org/CocoaPods-0.36/

> Caveats
One caveat about bundling resources is, that until now we had to embed all resources into the application bundle. The resources were referenced programmatically by [NSBundle mainBundle]. Pod authors were able to use mainBundle referencing to include resources the Pod brought into the app bundle. But with frameworks, you have to make sure that you reference them more specifically by getting a reference to your framework's bundle e.g.

Objective-C
` [NSBundle bundleForClass:<#ClassFromPodspec#>]`

Swift
`NSBundle(forClass: <#ClassFromPodspec#>)`

**Comment by bitomule** [comment]
Any update on this? Updated to 0.36 and can`t build my app.

**Comment by valeriomazzeo** [comment]
for the moment manually add the resource bundle of FormatterKit directly to the project, should solve the problem.

**Comment by bitomule** [comment]
Localizations folder? I don't know what should I add to my project. (btw, thanks)

**Comment by valeriomazzeo** [comment]
I am sorry, I confused that with DateTools which had the same problem.

I haven't tried with FormatterKit yet. The problem is that it tries to reference the resource with `[NSBundle mainBundle]` and instead now they are inside the FormatterKit framework bundle.

For the time being, try to import the localization folder into your project. That will add the resources to the main bundle and it should work until @mattt fixes it.

**Comment by bitomule** [comment]
Tried and still get this error: 
    
    error: open /Users/MyUser/Library/Developer/Xcode/DerivedData/myapp/Build/Products/Debug-iphonesimulator/Pods/FormatterKit.framework/el.lproj/FormatterKit.strings: No such file or directory

**Comment by bitomule** [comment]
Any update on this?

**Comment by bitomule** [comment]
I've added the Localizations folder to my app Resources and I get this error:

    error: make directory /Users/Bitomule/Library/Developer/Xcode/DerivedData/myApp-glftgsfullxjzugfqdpxizgvtcod/Build/Products/Debug-iphonesimulator/Pods/FormatterKit.framework/de.lproj: File exists

**Comment by bitomule** [comment]
I've created a pull request replacing mainBundle with bundleForClass. That should fix the issue no?

https://github.com/mattt/FormatterKit/pull/167

**Comment by tomoyuki28jp** [comment]
+1. I'm facing the same issue.

**Comment by tomoyuki28jp** [comment]
@bitomule When I try your code I get this error: `Use of undeclared identifier 'FormatterKit'`

**Comment by bitomule** [comment]
@tomoyuki28jp yeah, my code was wrong, don't know how to fix it :(

**Comment by cmorss** [comment]
I'm getting the same issue and not understanding how to do the proposed fix since I get this when the pods are being built. I needed to bump to the newer cocaopods version to get the native Socket.IO client, so jumping back a version is not an option.  Thanks for any pointers.

```
(null): error: make directory /Users/cmorss/Library/Developer/Xcode/DerivedData/Arrive-awwgmcgqkadbbueaookujpnajpxq/Build/Products/Debug-iphonesimulator/Pods/FormatterKit.framework/de.lproj: File exists
```

**Comment by fesnow** [comment]
This https://github.com/mattt/FormatterKit/pull/177 worked in my environment(cocoapods 0.36.4).

**Comment by cmorss** [comment]
Thanks, I'll give it a shot.

**Comment by yas375** [comment]
I think this has been fixed. Please try `1.8.1`.
